<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hcl" nsURI="http://www.example.org/hcl" nsPrefix="hcl">
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingUnit" eSuperTypes="#//Processing">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cores" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l1" lowerBound="1" eType="#//L1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l2" lowerBound="1" eType="#//L2"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="l3" lowerBound="1" eType="#//L3"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorageUnit" eSuperTypes="#//Storage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="storagedevice" lowerBound="1"
        upperBound="-1" eType="#//StorageDevice" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DisplayUnit" eSuperTypes="#//Display">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagonal" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloatObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" lowerBound="1"
        eType="#//DisplayType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DisplayType">
    <eLiterals name="HD" value="4"/>
    <eLiterals name="FullHD" value="1"/>
    <eLiterals name="FourK" value="2"/>
    <eLiterals name="FiveK" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StorageType">
    <eLiterals name="SSD" value="2"/>
    <eLiterals name="HDD" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorageDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" unique="false" lowerBound="1"
        eType="#//StorageType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CacheMagnitude">
    <eLiterals name="KiB" value="2"/>
    <eLiterals name="MiB" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="magnitude" unique="false"
        lowerBound="1" eType="#//CacheMagnitude"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingunit" lowerBound="1"
        eType="#//ProcessingUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="magnitude" unique="false"
        lowerBound="1" eType="#//CacheMagnitude"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingunit" lowerBound="1"
        eType="#//ProcessingUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L3">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" unique="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="magnitude" unique="false"
        lowerBound="1" eType="#//CacheMagnitude"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingunit" lowerBound="1"
        eType="#//ProcessingUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Computer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" upperBound="-1"
        eType="#//Component" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Processing" abstract="true" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="Display" abstract="true" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="DisplayRef" eSuperTypes="#//Display">
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayunit" lowerBound="1"
        eType="#//DisplayUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingRef" eSuperTypes="#//Processing">
    <eStructuralFeatures xsi:type="ecore:EReference" name="processingunit" lowerBound="1"
        eType="#//ProcessingUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Storage" abstract="true" eSuperTypes="#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="StorageRef" eSuperTypes="#//Storage">
    <eStructuralFeatures xsi:type="ecore:EReference" name="storageunit" lowerBound="1"
        eType="#//StorageUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
